### ISSUE TITLE
cannot use fd (type int) as type syscall.Handle in function argument

### ISSUE THREAD

**Issue by r-moeritz** [ngmoco/falcore#10]
This is basically a duplicate of issue #4. I would have re-opened it, but don't have permission.

```
C:\Users\Ralph\Temp>go version
go version go1
C:\Users\Ralph\Temp>go get github.com/ngmoco/falcore
# github.com/ngmoco/falcore
C:\Go\src\pkg\github.com\ngmoco\falcore\server.go:100: cannot use fd (type int) as type syscall.Handle in function argument
```

**Comment by dgrijalva** [comment]
Hrmmm...  It looks like the same issue we had before.  Might be time to split out the socket fd setup to separate files for windows and non-windows.

I'll see if I can get this fixed when I get home in a few hours.

**Comment by dgrijalva** [comment]
Sorry this has taken me so long.  I'm super duper busy and none of my projects at work are deploying on windows.  I'll be happy to review a patch from someone, or I'll get to this as soon as I have time.

As this is the second time we've hit this, I think the proper approach would be to break that one offending function out to a separate file and use the conditional inclusion syntax to make a windows specific version.  I'll have to read up on how that works.

**Comment by smw1218** [comment]
Thanks jameswynn!
