### ISSUE TITLE
Clean up Router API, document, and provide examples

### ISSUE THREAD

**Issue by JalfResi** [ngmoco/falcore#11]
The Router stuff needs to be updated, clarified, and documented.

Original request:

I've been poring over the source for falcore for a while now and I can't work out how Routes work, and their relationship with pipelines.

How do you add a route to a server? Can a route select a pipeline? etc;

A good clear, but simple example would go a long way to helping newbs like myself understand how all this works.

P.S. While I'm at it, a good clear example of how the Proxy/Upstream stuff works would rule too :)

**Comment by dgrijalva** [comment]
We need more examples.  I'll try to put some together soon.

The router stuff is not as clean as I'd like it to be. I have it on my todo list to clean it up.  The Router interface specifies one method, `SelectPipeline(req *Request)(pipe RequestFilter)`.  Pipelines are valid request filters, which explains the strange return type.

To use a router, insert it into the pipeline's Upstream.  Falcore will call SelectPipeline on your Router when it reaches that stage.  It will then traverse the returned pipeline.  Keep in mind that all Downstream filters will be executed on the way out.

Here's an extremely lazy example that would proxy requests beginning with /api/ and try to server anything else from disk:

```
pipe := falcore.NewPipeline()

upstream := upstream.NewUpstreamPool("foo", ...)
files := &static_file.Filter{BasePath: "/my/files/"}

router := falcore.NewPathRouter()
router.AddMatch("^/api/", upstream)
router.AddMatch(".*", files)

pipe.Upstream.PushBack(myAuthenticationFilter)
pipe.Upstream.PushBack(router)
```

I'm just using plain ol' RequestFilters here, but you can chain pipelines the same way.

**Comment by JalfResi** [comment]
Just tried out your example above and it works great! I get it now :)

**Comment by JalfResi** [comment]
Quick question:

Followed your instructions above, but the upstreamFilter doesnt seem to be proxying to the right backend. I'm running a simple API server at api.json.local:80, and my falcore server is on localhost:8000. I get the following log message:

2012/04/29 20:59:03 [DEBG] 7e907176e7 [GET] [api.test.local:80] http://localhost:8000/api/message.js s=403 Time=0.0006

And my code looks like:

```
var origin = []upstream.UpstreamEntryConfig {
    {HostPort:"api.test.local:80"},
}
upstreamPool := upstream.NewUpstreamPool("foo", origin)

router := falcore.NewPathRouter()
router.AddMatch("^/api/", upstreamPool)
```

It appears that my falcore server is proxying to http://localhost:8000/api/message.js rather than http://api.json.local:80/api/message.js as I would expect.

I use the following curl call:

curl "http://localhost:8000/api/message.js"

Both servers are on the same box, using /etc/hosts to map the domains to 127.0.0.1.

Does that make sense? Are my expectations correct?

**Comment by JalfResi** [comment]
Just to add, I added a weight:

var origin = []upstream.UpstreamEntryConfig {
    {HostPort:"api.test.local:80", Weight: 1},
}

but now the debug log states:

2012/04/29 21:14:13 [DEBG] 69a1c5867e [GET] [api.test.local:80] http://smallprox.local:8000/api/message.js s=403 Time=0.0012

note it is picking up the domain correctly from /etc/hosts now, but still is proxying to the wrong server.

I also added the following:

```
var origin = []upstream.UpstreamEntryConfig {
    {HostPort:"api.test.local:80", Weight: 1, ForceHttp: true, PingPath: "/api/message.js"},
}
```

Using the following curl command:

curl "http://api.test.local:80/api/message.js"

Brings back the response expected (JSON Doc)

However, the falcore sever outputs the following log messages:

2012/04/29 21:18:00 [FINE] Dialing connection to 127.0.0.1:80
2012/04/29 21:18:00 [EROR] Failed Ping to api.test.local:80: 403 Forbidden
2012/04/29 21:18:00 [INFO] Upstream foo: api.test.local:80  0
2012/04/29 21:18:01 [EROR] Failed Ping to api.test.local:80: 403 Forbidden
etc...

**Comment by dgrijalva** [comment]
Your config looks correct.  Are you sure the request isn't hitting your
upstream?  Are you sure it's reachable?

I believe the upstream does not change the hostname in the request, but it
should go to the right place.  This is usually desirable, since you'd
likely want to preserve the request details if you're using falcore as a
load balancer or reverse proxy or such.

What should happen is, the upstream should open a connection to your
specified host:port.  It should then forward requests along unmodified
(unless you've modified them elsewhere in the pipeline).  The hostname
information in the request is sent via the Host HTTP header.

I'm about to jump on a plane, but fire back if that doesn't help and I'll
see what I can do when I land (in like 15 hours).

-dave

On Sun, Apr 29, 2012 at 1:16 PM, JalfResi <
reply@reply.github.com

**Comment by JalfResi** [comment]
"I believe the upstream does not change the hostname in the request, but it
should go to the right place.  This is usually desirable, since you'd
likely want to preserve the request details if you're using falcore as a
load balancer or reverse proxy or such."

In light of that information, let me explain what I'm trying to do:

I have my falcore server sat on smallprox.local:8000. I have a JSON API on api.json.local:80.

api.json.local has a JSON file at /api/message.js. The following curl request works correctly:

curl "http://api.test.local:80/api/message.js"
{"message":"Hello, world!"}

I'd like to be able to make a call to http://smallprox.local:8000/api/message.js and have that be proxied to "http://api.test.local:80/api/message.js".

If the upstream doesn't change the hostname as per your description above, then yeah what I want to do wont work :)

I suppose I can maybe write a filter that sites infront of it that changes the hostname from smallprox.local to api.json.local? That would sort it out I think.

"What should happen is, the upstream should open a connection to your
specified host:port.  It should then forward requests along unmodified
(unless you've modified them elsewhere in the pipeline).  The hostname
information in the request is sent via the Host HTTP header."

If the upstream opens a connection to api.json.local and forwards the request along unmodified then that would explain the results I'm seeing, as both servers are on the same machine, and the url http://smallprox.local/api/message.js doesn't exist. However, surely I would expect to see the request looping, which I don't, so I don't know if the upstream modified the request with some kind of flag header of something to prevent this.

Seems I have some deep mis-understandings here! Sorry to waste your time with all this, especially if you are about to board a flight :)

Upstream stuff aside, I just want to add that I'm loving working with Falcore :) It's very straight forward and matches the way I think about servers (filters and streams) which I prefer over the Go HTTP stacked handlers route :)

**Comment by dgrijalva** [comment]
Glad you are enjoying it. The initial use case for falcore involved using different sets of servers to host different parts of an API. That's why the hostname isn't modified. 

Using a filter before the upstream should solve your problem. I'd also be willing to review a patch that made the an option within upstream. 

-dave

**Comment by JalfResi** [comment]
Ah, that makes sense.

Okay, I'll try and get a simple filter working, and then I'll fork and write a patch for the upstream (I'm thinking a simple boolean flag in the config would be great)

Thanks for your help, especially on a Sunday night :)

**Comment by smw1218** [comment]
Hey, sorry I missed this thread, I was on vacation.  It looks to me from your log that the original example is actually working as you would expect, but getting back a 403 error (forbidden).  The interpretation of the log is that the server in square brackets is the one with the tcp connection and the second is the one in the URL is from the Host HTTP header.

If rewriting the host works, then it's a bit weird.  Are you using named-based virtual hosts that would forbid access based on the HTTP host?

**Comment by JalfResi** [comment]
The setup I had was two servers on the same IP address: my falcore server and an apache server. The apache server was my json api server, and my falcore server was used to connect to the api apache server via the upstream filter and do some rewriting of the response (modify the JSON).

The problem is that the connection the upstream makes uses the host and port as specified, connecting via IP addres, after looking up the IP from the host. But the original request being push to the upstream still had the original Host header. I wanted the Host header to be re-written to match the api box, so that apache could use name based virtual hosts.

I understand that this use case differs from the way you guys have used the upstream filter in the past. It is my understanding that you would have a falcore server sitting in front of boxes that may never be made public, or may have the same host name. The situation I have is that I need the backend box to be public on its own host e.g. api.example.com and I want to write a falcore server to proxy requests to www.example.com to the api backend and rewrite the body of the response.

I hope that explains the motivations. The patch I submitted simply provides a boolean flag that will rewrite the host header to match to cover this use case.

**Comment by dgrijalva** [comment]
This issue got resolved as part of the pull request, right?
