### ISSUE TITLE
Do you have an example for adding a cookie to the response?

### ISSUE THREAD

**Issue by asogor** [ngmoco/falcore#19]

**Comment by dgrijalva** [comment]
Falcore doesn't currently provide utilities for working with cookies.  The built in http package includes some nice cookie utilities.  See http://golang.org/pkg/net/http/

I believe you could get away with something as simple as:

```
var myCookies []*http.Cookie

// insert some cookies into myCookies

for _, cookie := range myCookies {
   response.Header.Add("Set-Cookie", cookie.String())
}
```

Does that help?

**Comment by smw1218** [comment]
I'm assuming no response means the above suggestion worked.
