### ISSUE TITLE
attach falcore to a running http server

### ISSUE THREAD

**Issue by trungpham** [ngmoco/falcore#28]
rather than starting a new falcore server.

can I attach falcore to the started net/http server?

this way I can use falcore with google appengine.

thanks.

**Comment by smw1218** [comment]
The short answer is no.

The long answer is yes but you would have to write some code and possibly fork falcore to pull out the pieces you need.  When you say "attach falcore" I am assuming you want to use the Pipeline part without the HTTP server part.  Then execute the Pipeline inside a regular http.Handler.  Right now, this would require a few pieces of glue code:
1. The Pipeline has some setup for the stats and whatnot run by the server that are not an exposed API.  This would be simple to do with a fork and some cut and paste from server.go
2. A Pipeline returns an http.Response object while the http.Handler uses a http.ResponseWriter.  Using the http.Response to write with the http.ResponseWriter shouldn't be too hard but it doesn't currently exist.

I would be open to landing such modifications if they don't break any existing functionality.

Alternately you might be able to use the http.ReverseProxy to forward the requests directly to a falcore process.  I don't know how app engine works, but if you can run the falcore HTTP server directly, this might be an option.

**Comment by dgrijalva** [comment]
Using falcore with http.Server and Google App Engine is now possible with the latest falcore.

See: http://fitstar.github.io/falcore/compatibility.html
