### ISSUE TITLE
Failing file_filter_test.go

### ISSUE THREAD

**Issue by gnanderson** [ngmoco/falcore#29]
Hi guys,

This is more of a heads up, I've not quite got to the bottom of the problem yet.

After some tweaks to our core Go package RPM spec file, I was comfortable enough to re-enable building our Go repos for some other distros. A mime based file_filter test failed for the following distros:

```
https://build.opensuse.org/project/monitor?project=devel:languages:go
```
- CentOS 6 
-  RHEL 6
- ScientificLinux 6

Given that these three distro's are clones, I'll bet there's some problem with mime type detection on RHEL 6. If I find more, I'll update.

Cheers the noo,
Graham

**Comment by dgrijalva** [comment]
It certainly does look like the go standard library mime package isn't finding working on those systems.  That's not really a problem we should solve here, though it's worth opening a ticket on the go project.

I think we can get our tests passing by manually adding all of the types we care about to the lookup table.  That's probably a better solution anyway as it removed environment specific dependencies from our tests.

**Comment by dgrijalva** [comment]
I don't have access to those OSs to verify the fix.  Could you please run them again and let me know if it's fixed?

**Comment by gnanderson** [comment]
The failing test now passes for all three platforms, thanks.
