### ISSUE TITLE
Refactoring for benchmarks and testing.

### ISSUE THREAD

**Issue by gnanderson** [ngmoco/falcore#31]
Created this issue to discuss the possibility/likelyhood of getting a litte bit of refactoring commited. See this branch for the commits: https://github.com/gnanderson/falcore/tree/refactor

Will send pull requests to Dave and Scotts tree's for review.

This started off by a series of benchmarks using weighttpd against one of my own server binaries, I noticed that using weighttp with keep alive enabled gave a very unrealistically good score, but then I noticed that only half the requests were successful so there was something up server side. I tracked it down to the main server loop and the 'Connection' header check. While RFC2616 states that header field names should be case insensitive, it's vague about the header values and the upper case Keep-Alive check in the server loop was failing on every second request using weighttp.

So no problem, easy fix, but when I changed the header check to match lower case I noticed performance fall through the floor for persistent keep alive connections. I tracked that down to a combination of TCP_CORK plus the tweaked TCP stack setting on the linux box. With a bit of fiddling and some hit and miss I was back to my usual throughput.

Having said that, what I really missed was being able to bench the falcore.Server directly in the test suite. I started off trying to add a benchmark for falcore.Server, and this was OK for simple hello world filters but to use the file_filter meant the cyclic dependancy of importing file_filter which imports falcore which imports file_filter... made this impossible.

So one thing led to another, breaking the cyclic dependancy meant having to refactor the package imports, and api calls/references, and then it meant also refactoring the filter tests to work standalone without an http server, otherwise I would have been back to square one.

Anyway, there's a few things to look at in the refactored branch... Let me know what you think. It breaks the package imports for server binaries and there's a few API backwards incompatibilities, such things as each filter had a "Filter" struct which i renamed to FileFilter, CompressionFilter and so on.

Cheers the noo,
Graham

**Comment by smw1218** [comment]
Wow.  You've done some heavy lifting here.  There's some stuff I like and some stuff that I don't.

Like:
All the standard filters in the "filter" package with the consistent naming

Don't Like:
Core falcore functionality in the "filter" package
The request.go, response.go, filter.go (no need for the duplicate filter/logger.go)
This organization change is a show stopper for me, but I think we can meet in the middle.

I think there's an easy fix for the cyclical dependency.  Your test doesn't require any private falcore access so it should just be in a different package.  I think just renaming it to "falcore_integration" then importing falcore and the filters would fix it.

**Comment by smw1218** [comment]
your test needs no private dependencies with:
...

```
l.SetDeadline(time.Now().Add(3e9))
lfile, _ := l.File()
fd := int(lfile.Fd())
srv.FdListen(fd)
go srv.ListenAndServe()
```

instead of the private

go.listener = l
go.serve()

**Comment by gnanderson** [comment]
> Don't Like:
> Core falcore functionality in the "filter" package
> The request.go, response.go, filter.go (no need for the duplicate filter/logger.go)
> This organization change is a show stopper for me, but I think we can meet in the middle.

I grok that, looking at request.go for example, the functions there are really working with the pipeline which is core falcore functionality.

> I think there's an easy fix for the cyclical dependency. Your test doesn't require any private falcore access so it should just be in a different package. I think just renaming it to "falcore_integration" then importing falcore and the filters would fix it.

That's a good idea, I'll rework the branch and get back to you guys.

**Comment by dgrijalva** [comment]
Where did this end up?  I've been doing a bunch of cleanup.  I'd like to get all the changes in at once.

**Comment by smw1218** [comment]
I'd like to move all filters out of the falcore package into sub-packages.  This would have the side effect of forcing us to test like everyone else in the community so we might find more issues around testing.

I liked Graham's flat organization for the filters was pretty good so maybe we should do it that way: 

```
import "falcore/filter"
```

and you get them all.  That also forces some standard naming changes inside the filters.

**Comment by dgrijalva** [comment]
Which filters are not in subpackages?

Also, what is the benefit of a single "filter" package?

**Comment by smw1218** [comment]
See https://github.com/fitstar/falcore/pull/1

Having one sub-package where you can browse the included filters seems cleaner to me.  I'm not adamant though if you  think otherwise.

**Comment by gnanderson** [comment]
I'm afraid I can't offer any much more input on top of what's been said as I didn't find time to explore this any further :(

**Comment by smw1218** [comment]
This has been fixed/updated over at fitstar/falcore
