### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by marksteve** [ngmoco/falcore#37]

**Comment by dgrijalva** [comment]
Yessir. Need help with something?

-dave

**Comment by marksteve** [comment]
Nope. Just started with Go and this caught my eye. I just noticed the lack of activities. :)

**Comment by dgrijalva** [comment]
The project is pretty stable. Used in production under heavy load at a few companies. I have some new features nearly ready to land, but it will have to wait until I get out of crunch mode. 

Hope you enjoy go and falcore! We do.

-dave
