### ISSUE TITLE
Upstream deadline does not work correctly

### ISSUE THREAD

**Issue by smw1218** [ngmoco/falcore#41]
The upstream has a reference to a single *net.TCPConn which it uses to set the deadline just before calling transport.RoundTrip.  The transport will actually open new connections to the same server up to MaxIdleConnsPerHost if the current connection is already in use. Whenever a new connection is opened it overwrites the single reference.  When an old connection is reused later, it times-out since the deadline was set on the new connection instead of the older one being used.

I can't think of an easy way to fix this.  Maybe wrap the connection with one that checks a channel.  Send a flag to the channel in the same place as current deadline place and the first connection used will pop the channel and set the deadline only on the first write, otherwise no deadline is set.  I don't think this method is "thread" safe though.

Thoughts?

**Comment by dgrijalva** [comment]
Yikes.  Good catch.  What does the community say about timeouts using http.Transport?

**Comment by smw1218** [comment]
"Good" is subjective since your fix for Go 1 was a year ago and I only just now figured it out.  The only community post I saw was yours:

https://groups.google.com/forum/?fromgroups=#!searchin/golang-nuts/http.Transport$20timeout/golang-nuts/bCg-0vV2Nio/ysY3Z92rrnMJ

Having a 3k wait on a 3s timeout probably isn't great but realistically the conn is wrapped in bufio so in use it's more likely to be closer to the actual number.  Also, if we SetDeadline only on write, then that's probably close to what you want since it's usually slow responses that you want to protect.

I think to have a real timeout, we'd have to run the Roundtripper in a goroutine and have it race a time.Timer channel.
