### ISSUE TITLE
Falcore doesn't support Expect: 100-continue requests

### ISSUE THREAD

**Issue by smw1218** [ngmoco/falcore#43]
Apparently some of my recent issues arise from the smelly armpit of the HTTP spec:
http://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html#sec8.2.3

I need to falcore to handle requests with this header but this type of request breaks the 1 request to 1 response paradigm that we have use for the pipeline design.

There are a few things we can do:
1. Have the server send the 100 response immediately to the client then pass the request to the pipeline.  This is not exactly in the spirit of the "feature" since we never actually "determine if the origin server is willing to accept the request (based on the request headers)"
2. Run the pipeline twice. Once with the headers and let the pipeline/filters return the 100 status.  The server detects a 100 and sends the response and then immediately runs the pipeline again with the same request minus the Expect header.
3. We expose the connection directly in falcore.Request, so let the filters send the 100 response manually then return the real response as normal. This seems a bit lazy to me since the average developer (aka me) would not know to handle it.  But we could include an example of how to do it.

**Comment by dgrijalva** [comment]
What if we wrap the body in a thing that watches for a first read and performs the 100 continue functionality?

A falcore app that's ignorant of the 100 feature will work normally. An app that looks for the expectation can reject the request without reading the body.

-dave

**Comment by smw1218** [comment]
That sounds like a good idea. 
#3 is pretty trivial as well:

```
package continue_filter

import (
    "github.com/ngmoco/falcore"
    "net/http"
)

type Filter int

func (f Filter) FilterRequest(request *falcore.Request) (res *http.Response) {
    req := request.HttpRequest
    if req.Header.Get("Expect") == "100-continue" {
        resp := falcore.SimpleResponse(req, 100, nil, "")
        resp.Write(request.Connection)
        request.CurrentStage.Status = 0
    } else {
        request.CurrentStage.Status = 1
    }
    return nil
}
```

**Comment by smw1218** [comment]
So how should we handle it with the Upstream?  I guess since the Transport will soon ignore it, then we should just strip the header.

**Comment by dgrijalva** [comment]
Upstream can proxy the functionality:

1) look for expect header
2) write request headers to wire
3) wait for 100 continue
4) proxy body through

-dave

**Comment by smw1218** [comment]
With Brad's latest patch to transport, there would be no way to know about the 100 response and the transport would just start reading the body.  Maybe in the future if the transport supports the continue more fully we can tie into that.

**Comment by dgrijalva** [comment]
Something like this?

https://github.com/dgrijalva/falcore/commit/5f3cd840243f91fe7e09ec9a838d1a4c88aedf1c

-dave

**Comment by smw1218** [comment]
fixed everywhere now
