### ISSUE TITLE
Keep-Alive is not working

### ISSUE THREAD

**Issue by smw1218** [ngmoco/falcore#44]
not trolling, but ab doc says:

-k
Enable the HTTP KeepAlive feature, i.e., perform multiple requests within one HTTP session. Default is no KeepAlive.
gleecology commented

More to the point, after the first conn, it fails (even whilst adding the Connection: header):

--debug--

ab -v 6 -n 3 -c 1 -k http://localhost:8000/

This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/
Benchmarking localhost (be patient)...INFO: POST header ==
GET / HTTP/1.0
Connection: Keep-Alive
Host: localhost:8000
User-Agent: ApacheBench/2.3
Accept: /

LOG: header received:
HTTP/1.1 200 OK
Content-Length: 12

hello world!
LOG: Response code = 200
apr_poll: The timeout specified has expired (70007)

...To this ignorant layman, KA looks broken.

**Comment by smw1218** [comment]
I'll take a look on linux.  ab is notoriously broken on Mac OS so maybe what I was seeing was because of that.

**Comment by dgrijalva** [comment]
I just wrote a test for keep alive.  Seems to work well.  Could it be because `ab` uses `HTTP/1.0`?

https://github.com/dgrijalva/falcore/commit/19ea1c01aa12622e43980e5fe482345851627cea

**Comment by dgrijalva** [comment]
@gleecology Do you see anything amuck with my test that might explain the issue?

**Comment by dgrijalva** [comment]
I can also say that we're using falcore in production and keep-alive is very clearly working just fine.

**Comment by dgrijalva** [comment]
Might be relevant: http://www8.org/w8-papers/5c-protocols/key/key.html

**Comment by gleeco-cf** [comment]
First, has anybody been able to reproduce this condition? 

and yes, it would seem that HTTP 1.0 asking for Connection:keep-alive is awkward and unclear. 

http://blog.lolyco.com/sean/2009/11/25/ab-apache-bench-hanging-with-k-keep-alive-switch/

i stumbled in to this having used 'ab', and not realizing this bit of oddness.  fwiw, some proxies do exhibit this behavior, albeit non-std.

**Comment by smw1218** [comment]
I was able to reproduce and get a tcpdump of the output:
tcpdump -A -s0 -ilo "port 8000"

And ab is just never sending the next request.  falcore is keeping the connection alive until the ab timeout expires and that's the error you're getting.  As much as I like ab, it just hasn't been updated in forever.  Try siege or something that has better 1.1 support and I think the keep-alive will work just fine.

**Comment by smw1218** [comment]
ok... I added the header with a response filter:

```
var keepAlive = falcore.NewResponseFilter(func(req *falcore.Request, res *http.Response) {
    res.Header.Add("Connection", "Keep-Alive")
})
```

and now ab works!  tcpdump also confirms there's only one connection as well.  We'll patch falcore to add this automatically without the filter.
