### ISSUE TITLE
hot restart usage?

### ISSUE THREAD

**Issue by user974256** [ngmoco/falcore#46]
Could you please be so kind to explain how to use the hot restart functionality?

When sending SIGHUP to the `hot_restart` example binary, I receive an `address already in use` error like so:

```
./hot_restart 
47149 Received SIGHUP.  forking.
Forking now with socket: 7
47149 Forked pid: 47220 errno: <nil>
47220 Got socket FD: 7
47220 Could not start server: listen tcp <nil>:8090: address already in use47220 Exiting now
```

this is on osx 10.8

thanks a lot!

**Comment by smw1218** [comment]
I have seen this intermittently but everytime I try to investigate, it just goes away.  It appears to have something to do with  how go changes file descriptors during the ForkExec.  If this is consistent for you, I'll create a patch for you to try and see if it works.

**Comment by dgrijalva** [comment]
WFM™

```
$ bin/hot_restart 
46101 Received SIGHUP.  forking.
Forking now with socket: 7
46101 Forked pid: 46107 errno: <nil>
46107 Got socket FD: 7
46107 Kill parent 46101 with SIGUSR1
46101 Received SIGUSR1.  Stopping accept.
2013/04/11 10:03:33 [TRAC] Stopped accepting, waiting for handlers
46101 Exiting now
```

**Comment by user974256** [comment]
Thanks for the quick reply.

@smw1218 Yes, it's consistent for me, at least in so far that it survives reboots and also occures with older falcore revisions.

Maybe a race condition? It's happening on a mac book air with SSD - maybe ForkExec's timing is different here?

Some more background on the setup, I´m is using go from homebrew:

```
$ brew info go
go: stable 1.0.3, HEAD
```

I´ll happily test all patches you supply. This hot restart functionaliy is falcore`s unique selling point for me, I´d love to see it work.

**Comment by dgrijalva** [comment]
Huh.  I'm also on a macbook air and 10.8.  I can't make it happen.  I am on a slightly older go, though.  I'll update later today and give it another try.

```
go version go1.0.2
```

**Comment by smw1218** [comment]
can you try changing the hot_restart.go line 71 from
    args := []string{mypath, "-socket", fmt.Sprintf("%v", srv.SocketFd())}

to
    args := []string{mypath, "-socket", "3"}

**Comment by user974256** [comment]
now it's:

```
$ ./hot_restart 
2311 Received SIGHUP.  forking.
Forking now with socket: 7
2311 Forked pid: 2313 errno: <nil>
2313 Got socket FD: 3
2313 Kill parent 2311 with SIGUSR1
2311 Received SIGUSR1.  Stopping accept.
2013/04/11 19:40:57 [TRAC] Stopped accepting, waiting for handlers
2311 Exiting now
```

**Comment by smw1218** [comment]
Good... that means it worked ;)
If you do a ps, you'll see it still running and it should be responding to curl.  The ForkExec causes it to detach from the console.

**Comment by user974256** [comment]
Yes, looks good now. Its responds with "OK" to HTTP requests as its supposed to. Thanks!

**Comment by dgrijalva** [comment]
Are they re-numbering file pointers on fork-exec?!

**Comment by smw1218** [comment]
Yes, but they have always been doing that and my original implementation actually just used 3.  But that didn't work so I switched to the original one.  Looks like this changes in 1.0.3, I upgraded and now I can reproduce locally.

**Comment by dgrijalva** [comment]
I wrote up some documentation about hot restart functionality:  http://fitstar.github.io/falcore/hot_restart.html
