### ISSUE TITLE
Can this be used along with the Gorilla toolkit?

### ISSUE THREAD

**Issue by slantview** [ngmoco/falcore#53]
Was wondering if it is possible to use this in combination with the Gorilla web toolkit at http://www.gorillatoolkit.org/

Thanks!

**Comment by dgrijalva** [comment]
I haven't played much with Gorilla, but I'll bet you it can.  Is designed to stand alone, but it will happily sit at either end of the Go HTTP interface.  You can use the falcore http server bits to host a http.Handler or you can use falcore as an http.Handler.

For more info, look here: http://fitstar.github.io/falcore/compatibility.html

You may also find it's just as simple to do similar things by assembling just pipeline stages with falcore.

**Comment by slantview** [comment]
Hey, thanks for the reply.  I actually made it quite far with this.  You should update the ngmoco branch to point to the fitstar branch however, and could use a bit of documentation around routers and how to run HTTP/HTTPS simultaneously.  I got all that working, so I might contribute some docs/patches in the near future.  Keep up the good work!

**Comment by smw1218** [comment]
Thanks for the suggestions!  Patches are always welcome; I'm happy to hear it's working for you.

We are planning to discontinue the ngmoco branch but didn't quite get around to updating the readme yet.
